package com.borrowapp.common.constants;

public enum ActivityLogAction {

    // Auth
    USER_REGISTER, USER_LOGIN, LOGOUT, UPDATE_PROFILE, CHANGE_PASSWORD,

    // Equipment
    EQUIPMENT_CREATED, EQUIPMENT_UPDATED, EQUIPMENT_DELETED, EQUIPMENT_STOCK_UPDATED,
    CREATE_DEVICE, UPDATE_DEVICE, DELETE_DEVICE,

    // Request
    REQUEST_CREATED, REQUEST_APPROVED, REQUEST_REJECTED,
    REQUEST_RETURNED, REQUEST_MARKED_OVERDUE,
    CREATE_REQUEST, APPROVE_REQUEST, REJECT_REQUEST, RETURN_REQUEST, MARK_OVERDUE,

    // Penalty & Account
    PENALTY_ADDED, PENALTY_ADJUSTED, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,

    // Notification / Email
    EMAIL_SENT, EMAIL_FAILED, NOTIFICATION_CREATED, SEND_EMAIL, RETRY_EMAIL,

    // Admin
    EXPORT_DATA, IMPORT_DATA
}